name: CI-CD Pipeline

on:

  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:

  build:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - name: Build Application
        run: |
          echo "Building application..."
          sleep 5

  test:
    needs:
      - build  
    runs-on: ubuntu-latest

    steps:
      - name: Execute Test Cases
        run: |
          echo "Running tests..."
          sleep 5

  docker-build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker Image
        run: |
          echo "docker build -t myapp:v1 ."

  deploy:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Application
        run: |
          echo "Deploying application to Kubernetes"
          echo "kubectl apply -f deployment.yaml"

  verify:
